const products = [
  {
    id: 1,
    name: "Organic Bananas",
    category: "fruits",
    price: 2.99,
    image: "/fresh-organic-bananas.jpg",
    description: "Fresh organic bananas, perfectly ripe and sweet. Rich in potassium and natural energy.",
    details: [
      "Certified organic",
      "Imported from Ecuador",
      "Approximately 5-6 bananas per bunch",
      "High in potassium and fiber",
      "Perfect for smoothies and snacks",
    ],
  },
  {
    id: 2,
    name: "Fresh Strawberries",
    category: "fruits",
    price: 4.99,
    image: "/fresh-red-strawberries-in-container.jpg",
    description: "Sweet and juicy strawberries, locally grown and picked at peak ripeness.",
    details: [
      "Locally grown",
      "1 lb container",
      "No pesticides",
      "Rich in vitamin C",
      "Perfect for desserts and breakfast",
    ],
  },
  {
    id: 3,
    name: "Organic Spinach",
    category: "vegetables",
    price: 3.49,
    image: "/fresh-organic-spinach-leaves.jpg",
    description: "Fresh organic spinach leaves, perfect for salads, smoothies, or cooking.",
    details: [
      "Certified organic",
      "10 oz bag",
      "Pre-washed and ready to eat",
      "High in iron and vitamins",
      "Locally sourced",
    ],
  },
  {
    id: 4,
    name: "Cherry Tomatoes",
    category: "vegetables",
    price: 3.99,
    image: "/fresh-cherry-tomatoes-on-vine.jpg",
    description: "Sweet cherry tomatoes on the vine, bursting with flavor.",
    details: ["Vine-ripened", "1 pint container", "Greenhouse grown", "Perfect for salads", "Rich in antioxidants"],
  },
  {
    id: 5,
    name: "Whole Wheat Bread",
    category: "bakery",
    price: 4.49,
    image: "/fresh-whole-wheat-bread-loaf.jpg",
    description: "Freshly baked whole wheat bread, soft and nutritious. Made daily in our bakery.",
    details: ["Baked fresh daily", "100% whole wheat", "No artificial preservatives", "24 oz loaf", "High in fiber"],
  },
  {
    id: 6,
    name: "Organic Milk",
    category: "dairy",
    price: 5.99,
    image: "/organic-whole-milk-bottle.jpg",
    description: "Fresh organic whole milk from grass-fed cows. Rich and creamy.",
    details: [
      "Certified organic",
      "From grass-fed cows",
      "Half gallon (64 oz)",
      "No hormones or antibiotics",
      "Rich in calcium and vitamin D",
    ],
  },
  {
    id: 7,
    name: "Free-Range Eggs",
    category: "dairy",
    price: 6.49,
    image: "/free-range-eggs-in-carton.jpg",
    description: "Farm-fresh eggs from free-range chickens. Large brown eggs.",
    details: ["Free-range chickens", "Dozen large eggs", "Rich golden yolks", "High in protein", "From local farms"],
  },
  {
    id: 8,
    name: "Organic Chicken Breast",
    category: "meat",
    price: 12.99,
    image: "/fresh-organic-chicken-breast.jpg",
    description: "Premium organic chicken breast, boneless and skinless. Perfect for healthy meals.",
    details: [
      "Certified organic",
      "Boneless, skinless",
      "Approximately 1.5 lbs",
      "No antibiotics or hormones",
      "Raised humanely",
    ],
  },
  {
    id: 9,
    name: "Fresh Salmon Fillet",
    category: "seafood",
    price: 15.99,
    image: "/fresh-salmon-fillet.jpg",
    description: "Wild-caught salmon fillet, rich in omega-3 fatty acids.",
    details: [
      "Wild-caught",
      "Approximately 1 lb",
      "Rich in omega-3",
      "Sustainably sourced",
      "Perfect for grilling or baking",
    ],
  },
  {
    id: 10,
    name: "Organic Avocados",
    category: "fruits",
    price: 5.99,
    image: "/fresh-organic-avocados.jpg",
    description: "Creamy organic avocados, perfect for toast, salads, or guacamole.",
    details: ["Certified organic", "Pack of 4", "Ripe and ready to eat", "High in healthy fats", "Rich in vitamins"],
  },
  {
    id: 11,
    name: "Greek Yogurt",
    category: "dairy",
    price: 4.99,
    image: "/greek-yogurt-container.png",
    description: "Thick and creamy Greek yogurt, high in protein and probiotics.",
    details: [
      "Plain, unsweetened",
      "32 oz container",
      "High in protein",
      "Contains live cultures",
      "Made from organic milk",
    ],
  },
  {
    id: 12,
    name: "Artisan Sourdough",
    category: "bakery",
    price: 6.99,
    image: "/artisan-sourdough-loaf.png",
    description: "Handcrafted sourdough bread with a crispy crust and tangy flavor.",
    details: [
      "Baked fresh daily",
      "Traditional sourdough starter",
      "No commercial yeast",
      "Crusty exterior, soft interior",
      "Perfect for sandwiches",
    ],
  },
]
